version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-api
    working_dir: /var/www
    depends_on:
      - db
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    entrypoint: ["sh", "/var/www/entrypoint.sh"]
    restart: unless-stopped
      
  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - backend    

  frontend:
    build:
      context: ./frontend
    container_name: frontend-ui
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todo
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
